CREATE VIEW CONTRACTOR_INFO AS
    SELECT C.CONTRACTOR_NAME, DR.TI_NUM, R.RENT_DATE
    FROM CONTRACTOR C JOIN RENTAL R ON C.CONTRACTOR_NUM = R.CONTRACTOR_NUM
                      JOIN DETAILRENTAL DR ON R.RENT_NUM = DR.RENT_NUM
                      JOIN TOOLINSTANCE TI ON DR.TI_NUM = TI.TI_NUM;


CREATE VIEW RETAILER_INFO AS
    SELECT R.RETAILER_NAME, T.TOOL_NAME, T.TOOL_COST, (ROUND((SYSDATE - TI.TI_PURCHASEDATE)/365)) AS  "Number of Year bought", TI.TI_STATUS
    FROM RETAILER R JOIN TOOL T ON R.RETAILER_NUM = T.RETAILER_NUM
                    JOIN TOOLINSTANCE TI ON T.TOOL_NUM = TI.TOOL_NUM;

