--Create Table Contractor
CREATE TABLE CONTRACTOR
(
    CONTRACTOR_NUM NUMBER(10) PRIMARY KEY
        CONSTRAINT CONT_CONTRACTOR_NUM_NN NOT NULL,
    CONTRACTOR_NAME VARCHAR2(25)
        CONSTRAINT CONT_CONTRACTOR_NAME_NN NOT NULL,
    CONTRACTOR_PHONE_NUM VARCHAR2(15) 
        CONSTRAINT CONT_CONTRACTOR_PHONE_NUM_NN NOT NULL,  
    CONTRACTOR_ADDRESS_STREET VARCHAR2(100),
    CONTRACTOR_ADDRESS_CITY VARCHAR2(30),
    CONTRACTOR_ADDRESS_STATEPROV VARCHAR2(20) DEFAULT 'ON',
    CONTRACTOR_ADDDRESS_ZIP VARCHAR2(10), 
    CONTRACTOR_JOIN_DATE DATE DEFAULT SYSDATE 
        CONSTRAINT CONT_CONTRACTOR_JOIN_DATE_NN NOT NULL
);

--Create Table Retailer
CREATE TABLE RETAILER
(
    RETAILER_NUM NUMBER(10) NOT NULL
        CONSTRAINT RET_RETAILER_NUM_PK PRIMARY KEY,
    RETAILER_NAME VARCHAR2(30) 
        CONSTRAINT RET_RETAILER_NAME_NN NOT NULL
);                

--Create Table Tools
CREATE TABLE TOOL
(
    TOOL_NUM NUMBER(10) PRIMARY KEY
        CONSTRAINT TOOL_TOOLO_NUM_NN NOT NULL,
    TOOL_NAME VARCHAR2(100) 
        CONSTRAINT TOOL_TOOL_NAME_NN NOT NULL,
    TOOL_COST NUMBER(10,2)
        CONSTRAINT TOOL_TOOL_COST_CK CHECK(TOOL_COST >= 0),
    TOOL_LENGTH NUMBER(10,2)
        CONSTRAINT TOOL_TOOL_LENGTH_CK CHECK(TOOL_LENGTH >= 0),
    TOOL_WIDTH NUMBER(10,2)
        CONSTRAINT TOOL_TOOL_WIDTH_CK CHECK(TOOL_WIDTH >= 0),
    TOOL_HEIGHT NUMBER(10,2)
        CONSTRAINT TOOL_TOOL_HEIGHT_CK CHECK(TOOL_HEIGHT >= 0),
    TOOL_WEIGHTCLASS VARCHAR2(20)
        CONSTRAINT TOOL_TOOL_WEIGHTCLASS_CK CHECK(TOOL_WEIGHTCLASS IN ('LIGHT','MEDIUM','MEDIUN HEAVY','HEAVY','VERY HEAVY')),
    RETAILER_NUM NUMBER(10) 
        CONSTRAINT TOOL_RETAILER_NUM_NN NOT NULL,
        FOREIGN KEY (RETAILER_NUM) REFERENCES RETAILER(RETAILER_NUM)
);

--Create Table Tool Instance
CREATE TABLE TOOLINSTANCE
(
    TI_NUM NUMBER(10)PRIMARY KEY
        CONSTRAINT T_TI_NUM_NN NOT NULL,
    TOOL_NUM NUMBER(10)	
        CONSTRAINT T_TOOL_NUM_NN NOT NULL,
        FOREIGN KEY (TOOL_NUM) REFERENCES TOOL(TOOL_NUM),
    TI_PURCHASEDATE DATE DEFAULT SYSDATE
        CONSTRAINT T_TI_PURCHASEDATE_NN NOT NULL,
    TI_STATUS VARCHAR2(15) NOT NULL
        CONSTRAINT T_TI_STATUS_CK CHECK(TI_STATUS IN ('Available','Destroyed','Rented'))
);

--Create Table Rental
CREATE TABLE RENTAL
(
    RENT_NUM NUMBER(10)PRIMARY KEY
        CONSTRAINT RENTAL_RENT_NUM_NN NOT NULL,
    CONTRACTOR_NUM NUMBER(10)
        CONSTRAINT RENTAL_CONTRACTOR_NUM_NN NOT NULL,
        FOREIGN KEY (CONTRACTOR_NUM) REFERENCES CONTRACTOR(CONTRACTOR_NUM),
    RENT_DATE DATE DEFAULT SYSDATE
        CONSTRAINT RENTAL_RENT_DATE_NN NOT NULL
);

--Create Table Detail Rental
CREATE TABLE DETAILRENTAL
(
    RENT_NUM NUMBER(10)  
        CONSTRAINT DR_RENT_NUM_NN NOT NULL,
        FOREIGN KEY (RENT_NUM) REFERENCES RENTAL(RENT_NUM),
    TI_NUM NUMBER(10) 
        CONSTRAINT DR_TI_NUM NOT NULL,
        FOREIGN KEY (TI_NUM) REFERENCES TOOLINSTANCE(TI_NUM),
    DETAIL_FEE NUMBER(10)NOT NULL
        CONSTRAINT DR_D_FEE_CK CHECK(DETAIL_FEE >= 0),
    DETAIL_DAILYLATEFEE NUMBER(10) DEFAULT 100.00
        CONSTRAINT DR_D_DF_CK CHECK(DETAIL_DAILYLATEFEE >= 0),
    DETAIL_DUEDATE DATE
        CONSTRAINT DR_D_DD_NN NOT NULL,
    DETAIL_RETURNDATE DATE,
        PRIMARY KEY(RENT_NUM, TI_NUM)
);



