--Insert Values into Retailter Table (4 values)
INSERT INTO RETAILER(RETAILER_NUM, RETAILER_NAME)  VALUES (RETAILERS_NUM_SEQ.NEXTVAL,'John Deer');
INSERT INTO RETAILER(RETAILER_NUM, RETAILER_NAME)  VALUES (RETAILERS_NUM_SEQ.NEXTVAL,'XXX''s manufacturing');
INSERT INTO RETAILER(RETAILER_NUM, RETAILER_NAME)  VALUES (RETAILERS_NUM_SEQ.NEXTVAL,'Johnson');
INSERT INTO RETAILER(RETAILER_NUM, RETAILER_NAME)  VALUES (RETAILERS_NUM_SEQ.NEXTVAL,'YYY Tractors');

--Insert Values into Tool Table (4 values)
INSERT INTO TOOL
SELECT TOOLS_NUM_SEQ.NEXTVAL,'Tractor/mower',5001.99,100,20,150,'HEAVY', RETAILER_NUM FROM RETAILER WHERE RETAILER_NAME='John Deer';
INSERT INTO TOOL
SELECT TOOLS_NUM_SEQ.NEXTVAL,'Tree pruning shears',499.50,100,20,5,'MEDIUM',RETAILER_NUM FROM RETAILER WHERE RETAILER_NAME='XXX''s manufacturing';
INSERT INTO TOOL
SELECT TOOLS_NUM_SEQ.NEXTVAL,'Grass trimmer',150.89,100,30,30,'LIGHT',RETAILER_NUM FROM RETAILER WHERE RETAILER_NAME='Johnson';
INSERT INTO TOOL
SELECT TOOLS_NUM_SEQ.NEXTVAL,'Tractor',6000.00,100,30,200,'VERY HEAVY',RETAILER_NUM FROM RETAILER WHERE RETAILER_NAME='YYY Tractors';

--Insert Values into Contractor (4 values)
INSERT INTO CONTRACTOR
VALUES (CONTRACTORS_NUM_SEQ.nextval,'Carmen''s','905-111-2222','285 King Street','King City','ON', 'L5C 2X6', to_date('08-MAR-1990','DD-MON-YYYY'));
INSERT INTO CONTRACTOR
VALUES (CONTRACTORS_NUM_SEQ.nextval,'Audry''s','647-666-8888','86 Chu Street','North York','ON', 'M2A 4X9', to_date('18-JAN-1991','DD-MON-YYYY'));
INSERT INTO CONTRACTOR
VALUES (CONTRACTORS_NUM_SEQ.nextval,'John Adams','416-555-9999','234 Bloor W','Toronto','ON', 'M2S 4S3', to_date('05-JUL-2002','DD-MON-YYYY'));
INSERT INTO CONTRACTOR
VALUES (CONTRACTORS_NUM_SEQ.nextval,'ABC Contractors','416-123-4567','123 Pond Road','North York','ON', 'M3J 1P3', to_date('19-OCT-2016','DD-MON-YYYY'));

--Insert Values into Tool Instance Table (13 values)
INSERT INTO TOOLINSTANCE 
SELECT 11,tool_num, to_date('01-JAN-2012','DD-MON-YYYY'),'Destroyed' FROM TOOL WHERE TOOL.TOOL_NAME = 'Tractor/mower';
INSERT INTO TOOLINSTANCE 
SELECT 12,tool_num, to_date('01-JUL-2014','DD-MON-YYYY'),'Rented' FROM TOOL WHERE TOOL.TOOL_NAME = 'Tractor/mower';
INSERT INTO TOOLINSTANCE 
SELECT 13,tool_num, to_date('15-AUG-2016','DD-MON-YYYY'),'Available' FROM TOOL WHERE TOOL.TOOL_NAME = 'Tractor/mower';
INSERT INTO TOOLINSTANCE 
SELECT 14,tool_num, to_date('20-Aug-2016','DD-MON-YYYY'),'Available' FROM TOOL WHERE TOOL.TOOL_NAME = 'Tractor';
INSERT INTO TOOLINSTANCE 
SELECT 15,tool_num, to_date('20-Aug-2016','DD-MON-YYYY'),'Available' FROM TOOL WHERE TOOL.TOOL_NAME = 'Tractor';
INSERT INTO TOOLINSTANCE 
SELECT 16,tool_num, to_date('01-MAR-2013','DD-MON-YYYY'),'Rented' FROM TOOL WHERE TOOL.TOOL_NAME = 'Grass trimmer';
INSERT INTO TOOLINSTANCE 
SELECT 17,tool_num, to_date('03-APR-2014','DD-MON-YYYY'),'Rented' FROM TOOL WHERE TOOL.TOOL_NAME = 'Grass trimmer';
INSERT INTO TOOLINSTANCE 
SELECT 18,tool_num, to_date('05-MAY-2014','DD-MON-YYYY'),'Destroyed' FROM TOOL WHERE TOOL.TOOL_NAME = 'Grass trimmer';
INSERT INTO TOOLINSTANCE 
SELECT 19,tool_num, to_date('07-JUN-2015','DD-MON-YYYY'),'Destroyed' FROM TOOL WHERE TOOL.TOOL_NAME = 'Grass trimmer';
INSERT INTO TOOLINSTANCE 
SELECT 20,tool_num, to_date('09-JUL-2015','DD-MON-YYYY'),'Rented' FROM TOOL WHERE TOOL.TOOL_NAME = 'Grass trimmer';
INSERT INTO TOOLINSTANCE 
SELECT 21,tool_num, to_date('11-AUG-2016','DD-MON-YYYY'),'Rented' FROM TOOL WHERE TOOL.TOOL_NAME = 'Grass trimmer';
INSERT INTO TOOLINSTANCE 
SELECT 22,tool_num, to_date('01-MAY-2016','DD-MON-YYYY'),'Available' FROM TOOL WHERE TOOL.TOOL_NAME = 'Tree pruning shears';
INSERT INTO TOOLINSTANCE 
SELECT 23,tool_num, to_date('01-MAY-2016','DD-MON-YYYY'),'Available' FROM TOOL WHERE TOOL.TOOL_NAME = 'Tree pruning shears';

--Insert Values into Rental + Detail Rental Table (16 values (8 each))
INSERT INTO RENTAL 
SELECT RENTS_NUM_SEQ.nextval, contractor_num,to_date('01-FEB-2012','DD-MON-YYYY') FROM CONTRACTOR WHERE CONTRACTOR_NAME = 'Carmen''s';
INSERT INTO DETAILRENTAL
SELECT RENTS_NUM_SEQ.currval,11,100,20, to_date('01-AUG-2012','DD-MON-YYYY'),to_date('15-JUL-2012','DD-MON-YYYY') FROM SYS.DUAL;
INSERT INTO RENTAL 
SELECT RENTS_NUM_SEQ.nextval, contractor_num,to_date('15-JUL-2014','DD-MON-YYYY') FROM CONTRACTOR where CONTRACTOR_NAME = 'Carmen''s';
INSERT INTO DETAILRENTAL
SELECT RENTS_NUM_SEQ.currval,12,200,50, to_date('01-SEP-2015','DD-MON-YYYY'),to_date('30-AUG-2015','DD-MON-YYYY') FROM SYS.DUAL;
INSERT INTO RENTAL 
SELECT RENTS_NUM_SEQ.nextval, contractor_num,to_date('30-AUG-2015','DD-MON-YYYY') FROM CONTRACTOR WHERE CONTRACTOR_NAME = 'Carmen''s';
INSERT INTO DETAILRENTAL
SELECT RENTS_NUM_SEQ.currval,12,200,50, to_date('01-SEP-2016','DD-MON-YYYY'), null from sys.dual;
INSERT INTO RENTAL 
SELECT RENTS_NUM_SEQ.nextval, contractor_num,to_date('01-OCT-2016','DD-MON-YYYY') FROM CONTRACTOR WHERE CONTRACTOR_NAME = 'John Adams';
INSERT INTO DETAILRENTAL
SELECT RENTS_NUM_SEQ.currval,16,45,10, to_date('15-DEC-2016','DD-MON-YYYY'), null FROM sys.dual;
INSERT INTO RENTAL 
SELECT RENTS_NUM_SEQ.nextval, contractor_num,to_date('03-AUG-2015','DD-MON-YYYY') FROM CONTRACTOR WHERE CONTRACTOR_NAME = 'Audry''s';
INSERT INTO DETAILRENTAL
SELECT RENTS_NUM_SEQ.currval,17,50,10, to_date('01-OCT-2015','DD-MON-YYYY'), to_date('15-OCT-2015','DD-MON-YYYY') FROM sys.dual;
INSERT INTO RENTAL 
SELECT RENTS_NUM_SEQ.nextval, contractor_num,to_date('10-JUL-2015','DD-MON-YYYY') FROM CONTRACTOR WHERE CONTRACTOR_NAME = 'ABC Contractors';
INSERT INTO DETAILRENTAL
SELECT RENTS_NUM_SEQ.currval,20,50,10, to_date('01-SEP-2015','DD-MON-YYYY'), to_date('25-AUG-2015','DD-MON-YYYY') FROM sys.dual;
INSERT INTO RENTAL 
SELECT RENTS_NUM_SEQ.nextval, contractor_num,to_date('15-AUG-2016','DD-MON-YYYY') FROM CONTRACTOR WHERE CONTRACTOR_NAME = 'Audry''s';
INSERT INTO DETAILRENTAL
SELECT RENTS_NUM_SEQ.currval,21,50,10, to_date('01-NOV-2016','DD-MON-YYYY'), null FROM sys.dual;
INSERT INTO RENTAL 
SELECT RENTS_NUM_SEQ.nextval, contractor_num,to_date('01-MAR-2016','DD-MON-YYYY') FROM CONTRACTOR WHERE CONTRACTOR_NAME = 'John Adams';
INSERT INTO DETAILRENTAL
SELECT RENTS_NUM_SEQ.currval,20,55,15, to_date('01-AUG-2016','DD-MON-YYYY'), to_date('15-OCT-2016','DD-MON-YYYY') FROM sys.dual;
