document.write("<BR \/>");
document.write("		<h2 style=\"text-align:center\">Seneca College of Applied Arts and Technology<\/h2>");
document.write("		<BR \/>");
document.write("		<h2 style=\"text-align:center\">Welcome to ");
document.write("			<a style=\"color:#ff1493\">Khai Phan (bth645_201b24)'s<\/a> Web Site<\/h2>");
document.write("		<BR \/>");
document.write("<div class=\"custom-padding\">");
document.write("		<nav>");
document.write("			<div class=\"logo\">Khai Phan - BTH645<\/div>");
document.write("			<ul class=\"menu-area\">");
document.write("				<div class=\"dropdown\">");
document.write("				<li>");
document.write("					<a href=\"index.html\" style=\"font-size: 16px;\">HOMEPAGE<\/a>");
document.write("				<\/li>");
document.write("				<\/div>");
document.write("		");
document.write("				<div class=\"dropdown\">");
document.write("				<li>");
document.write("					<a style=\"font-size: 16px;\">Labs<\/a>");
document.write("					<div class=\"dropdown-content\">                        ");
document.write("						<a href=\"lab1.html\">Lab 1<\/a>");
document.write("						<a href=\"lab2.html\">Lab 2<\/a>");
document.write("						<a href=\"lab3.html\">Lab 3<\/a>");
document.write("						<a href=\"lab4.html\">Lab 4<\/a>");
document.write("						<a href=\"lab5.html\">Lab 5<\/a>");
document.write("						<a href=\"lab6.html\">Lab 6<\/a>");
document.write("					<\/div>");
document.write("				<\/li>");
document.write("				<\/div>");
document.write("								");
document.write("				<div class=\"dropdown\">");
document.write("				<li>");
document.write("					<a style=\"font-size: 16px;\">Assignments<\/a>");
document.write("					<div class=\"dropdown-content\">");
document.write("						<a href=\"assignment1.html\">Assignment 1<\/a>");
document.write("						<a href=\"assignment2.html\">Assignment 2<\/a>");
document.write("						<a href=\"assignment3.html\">Assignment 3<\/a>");
document.write("					<\/div>");
document.write("				<\/li>");
document.write("				<\/div>");
document.write("							");
document.write("				<div class=\"dropdown\">");
document.write("				<li>");
document.write("					<a style=\"font-size: 16px;\">Discussion<\/a>");
document.write("					<div class=\"dropdown-content\">");
document.write("						<a href=\"discussion1.html\">Web Usability<\/a>");
document.write("						<a href=\"discussion2.html\">Web Usability using TEXT<\/a>");
document.write("						<a href=\"discussion3.html\">Web Usability using IMAGE<\/a>");
document.write("						<a href=\"discussion4.html\">Web Usability using AUDIO<\/a>");
document.write("						<a href=\"a2sources.html\">Assignment 2 Source Usage<\/a>");
document.write("					<\/div>");
document.write("				<\/li>");
document.write("				<\/div>			");
document.write("			<\/ul>");
document.write("		<\/nav>");
document.write("		<\/div>");
        