DESCRIBE EMPLOYEES

SELECT EMPLOYEE_ID,LAST_NAME
FROM EMPLOYEES
WHERE MANAGER_ID = 124 AND SALARY > 3000;

SELECT DISTINCT REGION_ID
FROM COUNTRIES;

SELECT (COUNTRY_ID || ', ' || COUNTRY_NAME || ', ' || REGION_ID) AS COUNTRIES
FROM COUNTRIES
ORDER BY COUNTRY_ID DESC, REGION_ID ASC;

SELECT STREET_ADDRESS AS "STREET ADDRESS", CITY  
FROM LOCATIONS
WHERE CITY LIKE 'M%';

SELECT LAST_NAME, FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID = '&DEPARTMENT_ID';

SELECT FIRST_NAME, &NAME, &&NAME + 10
FROM EMPLOYEES;
UNDEFINE NAME

DEFINE LAST 
SELECT PHONE_NUMBER FROM EMPLOYEES WHERE LAST_NAME = '&LAST';
UNDEFINE LAST     
