SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME,ADD_MONTHS(HIRE_DATE, 240) AS "RETIREMENT DATE"
FROM EMPLOYEES
ORDER BY "RETIREMENT DATE" ASC;

SELECT TRUNC((TO_DATE('2017-12-25', 'YYYY-MM-DD')-SYSDATE)/7) AS WEEKS
FROM dual;

SELECT REPLACE(REPLACE(FIRST_NAME, 'S', '$'),'s','$') as change
FROM EMPLOYEES
WHERE INSTR(LOWER(FIRST_NAME),'s') > 0; 

SELECT LPAD(LAST_NAME,LENGTH(LAST_NAME)+3,'*') || RPAD(FIRST_NAME,30,'-') as "Employee Names"
FROM EMPLOYEES;

SELECT INITCAP(REPLACE(FIRST_NAME, 'e', 'he')) 
FROM EMPLOYEES;
