/* 1. the lifetime of a Java object
   2. garbage collection (JVM)
   updated on 1/09/2020
 */

public class LifeTime {

	private Employee w;
	private int      n;

	// the default constructor will be generated by the compiler

	public void change( ) {

		if ( w == null )

		     System.out.println( "w is a null reference!\n" );

		w = new Employee( 111, "Oh", "zzzzz", "2007"); // an object is created(heap storage)
	}

	public String toString() { // which class?

		String s = "<<<<<<< THE LIFETIME OF A JAVA OBJECT >>>>>>>\n\n";

        s += w; // what is w?

        s += "<<<<<<< n:" + n + " >>>>>>>";

        return s;
 	}

	public Employee foo() {

        System.out.println( "... create an object inside foo()..." );

      	Employee t = new Employee( 2, "Hi", "???", "345" ); // an object is created(heap storage)

		return t;
	}

	public static void main( String[] args ) {

		//create an instance of LifeTime named demo, default value has been initialized
	   LifeTime demo = new LifeTime();

		//trigger change() method, since nothing has been assign to w, it will trigger the System.out.println
		//then it will set w to type of Employee
	   demo.change();
		
		//display the toString() method in the LifeTime object, this time it will display the 
		//information of new Employee
	   System.out.println( demo );

		//print line statement
	   System.out.println( "......." );
	   
		//initialize a new Object d of type Employee, and make d = demo()
	   Employee d = demo.foo();

		//print line statement
	   System.out.println( d + "\n....... How many objects are still alive in the main?" );
	   
		//set d to null values
	   /* garbage collection on JVM */
	   d = null;
		//set d to new instances of Employee, trigger default constructor
	   d = new Employee();
		//display information
	   System.out.println(d);
	}
}