

 
CREATE TABLE DEP_CPY 
AS SELECT * FROM DEPARTMENTS 

INSERT INTO DEP_CPY  
VALUES (200, 'Programming', 201, NULL); 

INSERT INTO DEP_CPY (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, 
LOCATION_ID) 	
VALUES (210, 'Web design', NULL, 1700); 

SELECT USER AS "USER NAME", TO_CHAR(SYSDATE, 'HH:MI') AS "SERVER TIME", 
TO_CHAR(CURRENT_DATE, 'HH24:MI') AS "SESSION TIME"  FROM DUAL; 

UPDATE DEP_CPY 
SET MANAGER_ID = 103 
WHERE DEPARTMENT_NAME = 'Shipping'; 

UPDATE DEP_CPY 
SET MANAGER_ID = (SELECT MANAGER_ID FROM DEPARTMENTS WHERE 
DEPARTMENT_NAME = 'Sales'), 
LOCATION_ID = (SELECT LOCATION_ID FROM DEPARTMENTS WHERE 
DEPARTMENT_NAME = 'Sales') 
WHERE DEPARTMENT_NAME = 'Accounting' ; 
SELECT * FROM DEP_CPY; 

COMMIT; 

DELETE FROM DEP_CPY 
WHERE DEPARTMENT_NAME = 'Administration'; 
SELECT * FROM DEP_CPY; 

ROLLBACK;

DELETE FROM DEP_CPY 
WHERE DEPARTMENT_NAME = 'Administration'; 
SELECT * FROM DEP_CPY; 

CREATE TABLE MyTable  
              ( M_ID   INTEGER CHECK(M_ID >=1 AND M_ID <= 999) PRIMARY KEY, 
               M_DATE  DATE  DEFAULT SYSDATE, 
                M_SUBJECT  VARCHAR(100) UNIQUE); 
                
ROLLBACK;


ALTER TABLE MyTable 
ADD M_CODE CHAR(3) DEFAULT 'ABC';

DESCRIBE MyTable; 
 