function main = (
	delete objects
	c1 = cone wirecolor:green pos:[-20,0,0] radius1:5
	--c2 = cone wirecolor:blue pos:[0,0,0] radius1:5
	--c3 = cone wirecolor:red pos:[20,0,0] radius1:5
	--b1 = box length:50 width:5 height:5
	
	rotate c1 30[0,1,0]
	--rotate c2 30[0,-1,0]
	--rotate c2 30[0,-1,0]
	--rotate c3 30[1,1,1]
	
	--create a new pivot (vi? tri di chuyên)
	--b1.pivot=[0,25,0]
	--rotate b1 45[0,0,1]
	
)

main()